spring:
  application:
    name: ts-admin-service
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${random.int[1,99]}
        prefer-ip-address: true
      config:
        enabled: false
      host: localhost
      port: 8500

server:
  port: 8890